### ISSUE TITLE
azure-cli@0.9.15 network vnet list error

### ISSUE THREAD

**Issue by semkath** [Azure/azure-xplat-cli#2543]
The update to 0.9.15 broke various network commands for the azure-cli tools. In every case the error generated is as follows:

> { [Error: Cannot find module './vnetShowUtil'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './vnetShowUtil'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> ($NPM_DIR/lib/node_modules/azure-cli/lib/commands/arm/network/virtualNetwork._js:7:20)
    at Module._compile (module.js:413:34)
    at Module.pModule._compile ($NPM_DIR/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.streamliners._js [as ._js] ($NPM_DIR/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/underscored.js:120:12)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

This also affects "network nic show" and maybe other commands.
Workaround: Downgrade to 0.9.14

**Comment by romangromov** [comment]
@semkath thanks for reporting, can you please show full command which causes reported issue above so I can reproduce? Thanx!

**Comment by semkath** [comment]
@romangromov sure! For comparison 0.9.14 first:
`$ azure -v`
`0.9.14`
Run command to list virtual networks:
`$ azure network vnet list -v`
Result:
```
info:    Executing command network vnet list
verbose: Looking up virtual networks
data:    Name              Location    Resource group    Provisioning state  Address prefixes  DNS servers  Subnets number
data:    ----------------  ----------  ----------------  ------------------  ----------------  -----------  --------------
data:    [redacted]        westeurope  [redacted]        Succeeded           192.168.0.0/16                 2             
info:    network vnet list command OK
```

Now, let's update to 0.9.15:
`$ npm -g install azure-cli@0.9.15`
`$ azure -v`
`0.9.15`
Run command to list virtual networks again:
`$ azure network vnet list -v`
Result:
```
error:   Cannot find module './vnetShowUtil'
info:    Error information has been recorded to /$HOME/.azure/azure.err
```
The azure.err file contains the information given in the first post.

**Comment by romangromov** [comment]
@semkath can't repro this issue, working fine in `0.9.15`:

```
$ npm install azure-cli@0.9.15

$ node ./azure -v
0.9.15
$ node ./azure network vnet list
info:    Executing command network vnet list
+ Looking up virtual networks                                                  
data:    Name               Location       Resource group               Provisioning state  Address prefixes         DNS servers              Subnets number
data:    -----------------  -------------  ---------------------------  ------------------  -----------------------  -----------------------  --------------
data:    test               westus         clutst18605                  Succeeded           10.0.0.0/16                                       1             
data:    test               westus         clutst23302                  Succeeded           10.0.0.0/16                                       1             
data:    test               westus         clutst29324                  Succeeded           10.0.0.0/16     
```

You can try to completely re-install azure-cli,
hope this helps

**Comment by semkath** [comment]
@romangromov Completely removing azure-cli and reinstalling doesn't seem to help, the binary also looks fine. The issue doesn't occur with the code from this Github repository, only with 0.9.15 from npm. If I have time, I will investigate or just wait for 0.9.16 :) Thanks for listening to my problem!

**Comment by yugangw-msft** [comment]
@semkath , could you please delete the "~/streamline" folder and try again?

**Comment by yugangw-msft** [comment]
@amarzavery ,it appears 0.9.15 npm module contains streamline files, which is not correct. All sources published to npm should be pre-compiled.

**Comment by semkath** [comment]
@yugangw-msft Thanks for the suggestion. Removing the ~/.streamline folder worked!

**Comment by yugangw-msft** [comment]
@semkath, great.
@amarzavery , let us resolve this when we publish 0.9.16 out

**Comment by romangromov** [comment]
@yugangw-msft this can be closed, 0.9.16 published
