### ISSUE TITLE
ARM: azure vm list command fails

### ISSUE THREAD

**Issue by cdnjay** [Azure/azure-xplat-cli#2544]
Tool version 0.9.15

This works:
Current Mode: asm (Azure Service Management)
azure vm list
info:    Executing command vm list
+ Getting virtual machines
info:    No VMs found
info:    vm list command OK

This does not work on Mac (OS X 10.11.4 Build 15E39d) but it does work on Windows:
Current Mode: arm (Azure Resource Management)
azure vm list
info:    Executing command vm list
error:   msRest.addSerializationMixin is not a function
info:    Error information has been recorded to /Users/jtc/.azure/azure.err
error:   vm list command failed

2016-02-16T19:47:38.871Z:
{ [TypeError: msRest.addSerializationMixin is not a function]
  stack: [Getter/Setter],
  __frame:
   { name: '__3',
     line: 169,
     file: '/usr/local/azure/lib/commands/arm/vm/vm.js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 2,
     col: 15 },
  rawStack: [Getter] }
TypeError: msRest.addSerializationMixin is not a function
  <<< async stack >>>
    at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
    at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
    at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
    at VMClient.__.extend._getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
    at listVM__4 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:313:31)
  at __3 (/usr/local/azure/lib/commands/arm/vm/vm.js:171:16)
  <<< raw stack >>>
    at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
    at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
    at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
    at VMClient.__.extend._getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
    at __$listVM__4 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:313:31)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at VMClient.listVM__4 [as listVM] (/usr/local/azure/lib/commands/arm/vm/vmClient.js:311:202)
    at __$__3 (/usr/local/azure/lib/commands/arm/vm/vm.js:171:23)
    at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at AzureCli.__3 (/usr/local/azure/lib/commands/arm/vm/vm.js:164:406)

**Comment by amarzavery** [comment]
Please uninstall the azure-cli and do a fresh install.
If you installed via dmg then sudo azure-uninstall and install via the latest Mac installer again.

If installed via npm then
Npm uninstall azure-cli -g
Npm cache clear -g
Npm install azure-cli -g

Hope this helps.
Thanks,
Amar Zavery

On Feb 16, 2016, at 11:59 AM, "Jason Cruickshank" <notifications@github.com<mailto:notifications@github.com>> wrote:


Tool version 0.9.15

This works:
Current Mode: asm (Azure Service Management)
azure vm list
info: Executing command vm list

  *   Getting virtual machines info: No VMs found info: vm list command OK

This does not work on Mac (OS X 10.11.4 Build 15E39d) but it does work on Windows:
Current Mode: arm (Azure Resource Management)
azure vm list
info: Executing command vm list
error: msRest.addSerializationMixin is not a function
info: Error information has been recorded to /Users/jtc/.azure/azure.err
error: vm list command failed

2016-02-16T19:47:38.871Z:
{ [TypeError: msRest.addSerializationMixin is not a function]
stack: [Getter/Setter],
frame:
{ name: '__3',
line: 169,
file: '/usr/local/azure/lib/commands/arm/vm/vm.js',
prev: undefined,
calls: 1,
active: false,
offset: 2,
col: 15 },
rawStack: [Getter] }
TypeError: msRest.addSerializationMixin is not a function
<<< async stack >>>
at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
at VMClient..extend.getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
at listVM__4 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:313:31)
at __3 (/usr/local/azure/lib/commands/arm/vm/vm.js:171:16)
<<< raw stack >>>
at new NetworkManagementClient (/usr/local/azure/node_modules/azure-arm-network/lib/networkManagementClient.js:108:10)
at Object.exports.createAutoRestClient (/usr/local/azure/lib/util/utils.js:91:16)
at Object.exports.createNetworkManagementClient (/usr/local/azure/lib/util/utils.js:241:15)
at VMClient._.extend.getServiceClients (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1463:44)
at _$listVM__4 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:313:31)
at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
at VMClient.listVM__4 as listVM</usr/local/azure/lib/commands/arm/vm/vmClient.js:311:202>
at __$__3 (/usr/local/azure/lib/commands/arm/vm/vm.js:171:23)
at __func (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:47:5)
at AzureCli.__3 (/usr/local/azure/lib/commands/arm/vm/vm.js:164:406)

-

**Comment by cdnjay** [comment]
This worked, thanks.
