### ISSUE TITLE
azure-cli 0.9.0 fails to run in OS X 10.10.3 - env: node\r: No such file or directory

### ISSUE THREAD

**Issue by phairoh** [Azure/azure-xplat-cli#1725]
After updating through npm today azure-cli fails to run in OS X 10.10.3.  I receive the following output when running it from the terminal:

```bash
$ azure
env: node\r: No such file or directory
```
Reproduction steps:
1. Be using OS X 10.10.3
2. Install azure-cli globally
   `$npm install -g azure-cli`
3. Run azure-cli
   `$azure`

I also tried this in Windows 10 and the command ran successfully.  Additionally I attempted to run this in an OS X 10.10.3 VM that I keep clean to test stuff like this and it gave me the same error.

Some research led me to find that it likely has something to do with DOS vs UNIX line endings.  To fix this I opened `./bin/azure` in `vim` and used the command: `:set ff=unix` and saved the file.  When next I ran `azure` I received the following message (brackets are my own):

```bash
$ azure
error:   Cannot find module './account/accountclient'
info:    Error information has been recorded to [~]/.azure/azure.err
```

The content of azure.err are as follows:
```
Wed Apr 29 2015 18:47:41 GMT-0400 (EDT):
{ [Error: Cannot find module './account/accountclient'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './account/accountclient'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-cli/lib/commands/account._js:12:21)
    at Module._compile (module.js:460:26)
    at Module.pModule._compile (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/register.js:72:15)
    at Object.streamliners._js [as ._js] (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/compiler/underscored.js:120:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
I tried to determine what the cause of this error was but was unsuccessful.  I've tried uninstalling and reinstalling multiple ways but nothing I have tried yet has worked.

Rolling back to 0.8.17 is a workaround at this time as it seems to function as expected.

Update: I decided to try one more thing and cloned the repo locally, ensured that I was on the dev branch (as that seems to be the one that was pushed to npm) and ran `./bin/azure`.  The command ran without error.  Now I'm completely baffled...

**Comment by yugangw-msft** [comment]
thanks for reporting this issue, we have published a new version on npm which resolved this issue. Could you please verify?

**Comment by tmm1** [comment]
Confirmed this is fixed after upgrading to 0.9.1

**Comment by phairoh** [comment]
Confirmed as well.  Thank you for the quick fix!
